
const ArcaneReference = [
    "Arcane Acceleration",
    "Arcane Aegis",
    "Arcane Agility",
    "Arcane Arachne",
    "Arcane Avenger",
    "Arcane Awakening",
    "Arcane Barrier",
    "Arcane Battery",
    "Arcane Bellicose",
    "Arcane Blade Charger",
    "Arcane Blessing",
    "Arcane Bodyguard",
    "Arcane Camisado",
    "Arcane Consequence",
    "Arcane Crepuscular",
    "Arcane Deflection",
    "Arcane Double Back",
    "Arcane Energize",
    "Arcane Eruption",
    "Arcane Escapist",
    "Arcane Fury",
    "Arcane Grace",
    "Arcane Guardian",
    "Arcane Healing",
    "Arcane Hot Shot",
    "Arcane Ice",
    "Arcane Ice Storm",
    "Arcane Impetus",
    "Arcane Intention",
    "Arcane Momentum",
    "Arcane Nullifier",
    "Arcane Phantasm",
    "Arcane Pistoleer",
    "Arcane Power Ramp",
    "Arcane Precision",
    "Arcane Primary Charger",
    "Arcane Pulse",
    "Arcane Rage",
    "Arcane Reaper",
    "Arcane Resistance",
    "Arcane Rise",
    "Arcane Steadfast",
    "Arcane Strike",
    "Arcane Tanker",
    "Arcane Tempo",
    "Arcane Trickery",
    "Arcane Truculence",
    "Arcane Ultimatum",
    "Arcane Universal Fallout",
    "Arcane Velocity",
    "Arcane Victory",
    "Arcane Warmth",

    "Molt Augmented",
    "Molt Efficiency",
    "Molt Reconstruct",
    "Molt Vigor",

    "Melee Afflictions",
    "Melee Animosity",
    "Melee Crescendo",
    "Melee Doughty",
    "Melee Duplicate",
    "Melee Exposure",
    "Melee Fortification",
    "Melee Influence",
    "Melee Retaliation",
    "Melee Vortex",
   
];

export default ArcaneReference;