


const images = import.meta.glob('../assets/images/Warframe/PS_imgs/*.webp', { eager: true });


const getImg = (name: string) => {
  const entry = Object.entries(images).find(([path]) =>
    path.toLowerCase().includes(name.toLowerCase())
  );
  return entry ? (entry[1] as { default: string }).default : undefined;
};



const PrimeSetsArray = {
    AshPrime: {type: "warframe", img: getImg("AshPrime")},
    AtlasPrime: {type: "warframe", img: getImg("AtlasPrime")},
    BansheePrime: {type: "warframe", img: getImg("BansheePrime")},
    BaruukPrime: {type: "warframe", img: getImg("BaruukPrime")},
    ChromaPrime: {type: "warframe", img: getImg("ChromaPrime")},
    EmberPrime: {type: "warframe", img: getImg("EmberPrime")},
    EquinoxPrime: {type: "warframe", img: getImg("EquinoxPrime")},
    FrostPrime: {type: "warframe", img: getImg("FrostPrime")},
    GaraPrime: {type: "warframe", img: getImg("GaraPrime")},
    GarudaPrime: {type: "warframe", img: getImg("GarudaPrime")},
    GaussPrime: {type: "warframe", img: getImg("GaussPrime")},
    GrendelPrime: {type: "warframe", img: getImg("GrendelPrime")},
    HarrowPrime: {type: "warframe", img: getImg("HarrowPrime")},
    HildrynPrime: {type: "warframe", img: getImg("HildrynPrime")},
    HydroidPrime: {type: "warframe", img: getImg("HydroidPrime")},
    InarosPrime: {type: "warframe", img: getImg("InarosPrime")},
    IvaraPrime: {type: "warframe", img: getImg("IvaraPrime")},
    KhoraPrime: {type: "warframe", img: getImg("KhoraPrime")},
    LavosPrime: {type: "warframe", img: getImg("LavosPrime")},
    LimboPrime: {type: "warframe", img: getImg("LimboPrime")},
    LokiPrime: {type: "warframe", img: getImg("LokiPrime")},
    MagPrime: {type: "warframe", img: getImg("MagPrime")},
    MesaPrime: {type: "warframe", img: getImg("MesaPrime")},
    MiragePrime: {type: "warframe", img: getImg("MiragePrime")},
    NekrosPrime: {type: "warframe", img: getImg("NekrosPrime")},
    NezhaPrime: {type: "warframe", img: getImg("NezhaPrime")},
    NidusPrime: {type: "warframe", img: getImg("NidusPrime")},
    NovaPrime: {type: "warframe", img: getImg("NovaPrime")},
    NyxPrime: {type: "warframe", img: getImg("NyxPrime")},
    OberonPrime: {type: "warframe", img: getImg("OberonPrime")},
    OctaviaPrime: {type: "warframe", img: getImg("OctaviaPrime")},
    ProteaPrime: {type: "warframe", img: getImg("ProteaPrime")},
    RevenantPrime: {type: "warframe", img: getImg("RevenantPrime")},
    RhinoPrime: {type: "warframe", img: getImg("RhinoPrime")},
    SarynPrime: {type: "warframe", img: getImg("SarynPrime")},
    SevagothPrime: {type: "warframe", img: getImg("SevagothPrime")},
    TitaniaPrime: {type: "warframe", img: getImg("TitaniaPrime")},
    TrinityPrime: {type: "warframe", img: getImg("TrinityPrime")},
    ValkyrPrime: {type: "warframe", img: getImg("ValkyrPrime")},
    VaubanPrime: {type: "warframe", img: getImg("VaubanPrime")},
    VoltPrime: {type: "warframe", img: getImg("VoltPrime")},
    WispPrime: {type: "warframe", img: getImg("WispPrime")},
    WukongPrime: {type: "warframe", img: getImg("WukongPrime")},
    XakuPrime: {type: "warframe", img: getImg("XakuPrime")},
    ZephyrPrime: {type: "warframe", img: getImg("ZephyrPrime")},
    


    AcceltraPrime: {type: "rifle", img: getImg("AcceltraPrime")},
    AstillaPrime: {type: "rifle", img: getImg("AstillaPrime")},
    BazaPrime: {type: "rifle", img: getImg("BazaPrime")},
    BoarPrime: {type: "rifle", img: getImg("BoarPrime")},
    BoltorPrime: {type: "rifle", img: getImg("BoltorPrime")},
    BratonPrime: {type: "rifle", img: getImg("BratonPrime")},
    BurstonPrime: {type: "rifle", img: getImg("BurstonPrime")},
    CedoPrime: {type: "rifle", img: getImg("CedoPrime")},
    CernosPrime: {type: "bow", img: getImg("CernosPrime")},
    CorinthPrime: {type: "rifle", img: getImg("CorinthPrime")},
    FulminPrime: {type: "rifle", img: getImg("FulminPrime")},
    LatronPrime: {type: "rifle", img: getImg("LatronPrime")},
    NagantakaPrime: {type: "rifle", img: getImg("NagantakaPrime")},
    PantheraPrime: {type: "rifle", img: getImg("PantheraPrime")},
    ParisPrime: {type: "bow", img: getImg("ParisPrime")},
    PhantasmaPrime: {type: "rifle", img: getImg("PhantasmaPrime")},
    RubicoPrime: {type: "rifle", img: getImg("RubicoPrime")},
    ScourgePrime: {type: "speargun", img: getImg("ScourgePrime")},
    SomaPrime: {type: "rifle", img: getImg("SomaPrime")},
    StradavarPrime: {type: "rifle", img: getImg("StradavarPrime")},
    StrunPrime: {type: "rifle", img: getImg("StrunPrime")},
    SybarisPrime: {type: "rifle", img: getImg("SybarisPrime")},
    TenoraPrime: {type: "rifle", img: getImg("TenoraPrime")},
    TiberonPrime: {type: "rifle", img: getImg("TiberonPrime")},
    TigrisPrime: {type: "rifle", img: getImg("TigrisPrime")},
    TrumnaPrime: {type: "rifle", img: getImg("TrumnaPrime")},
    VectisPrime: {type: "rifle", img: getImg("VectisPrime")},
    ZhugePrime: {type: "crossbow", img: getImg("ZhugePrime")},



    AfurisPrime: {type: "dualpistols", img: getImg("AfurisPrime")},
    AkariusPrime: {type: "dualpistols", img: getImg("AkariusPrime")},
    AkboltoPrime: {type: "dualpistols", img: getImg("AkboltoPrime")},
    AkbroncoPrime: {type: "dualpistolsbaro", img: getImg("AkbroncoPrime")},
    AkjagaraPrime: {type: "dualpistols", img: getImg("AkjagaraPrime")},
    AklexPrime: {type: "dualpistolsbaro", img: getImg("AklexPrime")},
    AkmagnusPrime: {type: "dualpistolsbaro", img: getImg("AkmagnusPrime")},
    AksomatiPrime: {type: "dualpistols", img: getImg("AksomatiPrime")},
    AkstilettoPrime: {type: "dualpistols", img: getImg("AkstilettoPrime")},
    AkvastoPrime: {type: "dualpistolsbaro", img: getImg("AkvastoPrime")},
    BallisticaPrime: {type: "crossbowpistol", img: getImg("BallisticaPrime")},
    BroncoPrime: {type: "pistol", img: getImg("/BroncoPrime")},
    EpitaphPrime: {type: "pistol", img: getImg("EpitaphPrime")},
    EuphonaPrime: {type: "pistol", img: getImg("EuphonaPrime")},
    HikouPrime: {type: "thrown", img: getImg("HikouPrime")},
    HystrixPrime: {type: "pistol", img: getImg("HystrixPrime")},
    KnellPrime: {type: "pistol", img: getImg("KnellPrime")},
    LexPrime: {type: "pistol", img: getImg("/LexPrime")},
    MagnusPrime: {type: "pistol", img: getImg("/MagnusPrime")},
    PanderoPrime: {type: "pistol", img: getImg("PanderoPrime")},
    PyranaPrime: {type: "pistol", img: getImg("PyranaPrime")},
    SicarusPrime: {type: "pistol", img: getImg("SicarusPrime")},
    SpiraPrime: {type: "thrown", img: getImg("SpiraPrime")},
    VastoPrime: {type: "pistol", img: getImg("/VastoPrime")},
    VeloxPrime: {type: "pistol", img: getImg("VeloxPrime")},
    ZaktiPrime: {type: "pistol", img: getImg("ZaktiPrime")},
    ZylokPrime: {type: "pistol", img: getImg("ZylokPrime")},

    AnkyrosPrime: {type: "dualblades", img: getImg("AnkyrosPrime")},
    BoPrime: {type: "staff", img: getImg("BoPrime")},
    Cobra_and_CranePrime: {type: "swordshield", img: getImg("Cobra_and_CranePrime")},
    DakraPrime: {type: "sword", img: getImg("DakraPrime")},
    DestrezaPrime: {type: "sword", img: getImg("DestrezaPrime")},
    DualKamasPrime: {type: "dualblades", img: getImg("DualKamasPrime")},
    DualKeresPrime: {type: "dualblades", img: getImg("DualKeresPrime")},
    FangPrime: {type: "dualblades", img: getImg("FangPrime")},
    FragorPrime: {type: "sword", img: getImg("FragorPrime")},
    GalatinePrime: {type: "sword", img: getImg("GalatinePrime")},
    GlaivePrime: {type: "dualblades", img: getImg("GlaivePrime")},
    GramPrime: {type: "sword", img: getImg("GramPrime")},
    GuandaoPrime: {type: "dualblades", img: getImg("GuandaoPrime")},
    GunsenPrime: {type: "dualblades", img: getImg("GunsenPrime")},
    KarystPrime: {type: "sword", img: getImg("KarystPrime")},
    KogakePrime: {type: "dualblades", img: getImg("KogakePrime")},
    KronenPrime: {type: "dualblades", img: getImg("KronenPrime")},
    MasseterPrime: {type: "sword", img: getImg("MasseterPrime")},
    NamiSkylaPrime: {type: "dualblades", img: getImg("NamiSkylaPrime")},
    NikanaPrime: {type: "sword", img: getImg("NikanaPrime")},
    NinkondiPrime: {type: "dualblades", img: getImg("NinkondiPrime")},
    OkinaPrime: {type: "dualblades", img: getImg("OkinaPrime")},
    OrthosPrime: {type: "dualblades", img: getImg("OrthosPrime")},
    PangolinPrime: {type: "sword", img: getImg("PangolinPrime")},
    QuassusPrime: {type: "dualblades", img: getImg("QuassusPrime")},
    ReaperPrime: {type: "sword", img: getImg("ReaperPrime")},
    RedeemerPrime: {type: "sword", img: getImg("RedeemerPrime")},
    ScindoPrime: {type: "sword", img: getImg("ScindoPrime")},
    Silva_and_AegisPrime: {type: "dualblades", img: getImg("Silva_and_AegisPrime")},
    TatsuPrime: {type: "sword", img: getImg("TatsuPrime")},
    TekkoPrime: {type: "dualblades", img: getImg("TekkoPrime")},
    TipedoPrime: {type: "dualblades", img: getImg("TipedoPrime")},
    VenkaPrime: {type: "dualblades", img: getImg("VenkaPrime")},
    VolnusPrime: {type: "sword", img: getImg("VolnusPrime")},

    CorvasPrime: {type: "rifle", img: getImg("CorvasPrime")},
    LarkspurPrime: {type: "rifle", img: getImg("LarkspurPrime")},

    CarrierPrime: {type: "warframe", img: getImg("CarrierPrime")},
    DethcubePrime: {type: "warframe", img: getImg("DethcubePrime")},
    HeliosPrime: {type: "warframe", img: getImg("HeliosPrime")},
    NautilusPrime: {type: "warframe", img: getImg("NautilusPrime")},
    ShadePrime: {type: "warframe", img: getImg("ShadePrime")},
    WyrmPrime: {type: "warframe", img: getImg("WyrmPrime")},

    KavasaPrimeCollar: {type: "collar", img: getImg("KavasaPrimeCollar")},

    OdonataPrime: {type: "archwing", img: getImg("OdonataPrime")},
};

export default PrimeSetsArray;